version: '3'
services:
    laravel.blogx:
        image: rumi87/blogx:${GIT_COMMIT_SHORT}
        ports:
            - 8000:8000
        env_file: .env.example
        networks:
            - blogx
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        env_file: .env.example
        volumes:
            - 'blogxmysql:/var/lib/mysql'
        networks:
            - blogx
networks:
    blogx:
        driver: bridge
volumes:
    blogxmysql:
        driver: local
